[package]
name = "os"
description = "A badly written Operating System with too many bugs"
readme = "README.md"
repository = "https://github.com/"
license = "MIT"
version = "0.0.0"
authors = ["dfs"]
edition = "2018"

[dependencies]
r-efi = "4.0.0"

[lib]
name = "kernel"
