#!/bin/bash
if [[ -n `echo $1 | grep x86_64` ]]; then
    file="BOOTx64"
    arch="x86_64"
elif [[ -n `echo $1 | grep aarch64` ]]; then
    file="BOOTAA64"
    arhc="x86_64"
fi
cp $1 iso/EFI/BOOT/$file.efi
qemu-system-$arch -enable-kvm -bios OVMF.fd -m 128 -nographic -drive format=raw,file=fat:rw:iso
