[build]
target = "x86_64-unknown-uefi"
rustflags = ["-Clink-arg=/DEBUG:DWARF"]

[unstable] 
build-std = ["core"]

[alias]
bb = "build --release"
rr = "run --release"

[target.x86_64-unknown-uefi]
runner = "./qemu"

[target.aarch64-unknown-uefi]
runner = "./qemu"
